### ISSUE TITLE
git-crypt does not compile on older Mac OS versions (10.8 or older)

### ISSUE THREAD

**Issue by Aeon** [AGWA/git-crypt#40]
Error log:
```
git-crypt-0.4.2 
$ make
c++ -Wall -pedantic -Wno-long-long -O2   -c -o util.o util.cpp
In file included from util.cpp:129:
./util-unix.cpp:322:12: error: no matching function for call to 'scandir'
        int                     n = scandir(path, &namelist, dirfilter, alphasort);
                                    ^~~~~~~
/usr/include/dirent.h:128:5: note: candidate function not viable: no known conversion from 'int (const struct dirent *)' to 'int (*)(struct dirent *)' for 3rd argument;
int scandir(const char *, struct dirent ***,
    ^
1 error generated.
make: *** [util.o] Error 1
```

A quick search turns up https://github.com/Homebrew/homebrew/issues/13649 - seems like scandir has to be defined by our source for older OS?

**Comment by AGWA** [comment]
Thanks for reporting this.  Could you try checking out the readdir branch and seeing if it compiles?

**Comment by Aeon** [comment]
Seems to compile with some warnings:

```
crypto-openssl.cpp:45:2: warning: 'ERR_load_crypto_strings' is deprecated [-Wdeprecated-declarations]
        ERR_load_crypto_strings();
        ^
/usr/include/openssl/err.h:296:6: note: 'ERR_load_crypto_strings' declared here
void ERR_load_crypto_strings(void) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
crypto-openssl.cpp:55:6: warning: 'AES_set_encrypt_key' is deprecated [-Wdeprecated-declarations]
        if (AES_set_encrypt_key(raw_key, KEY_LEN * 8, &(impl->key)) != 0) {
            ^
/usr/include/openssl/aes.h:92:5: note: 'AES_set_encrypt_key' declared here
int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
    ^
crypto-openssl.cpp:70:2: warning: 'AES_encrypt' is deprecated [-Wdeprecated-declarations]
        AES_encrypt(plain, cipher, &(impl->key));
        ^
/usr/include/openssl/aes.h:97:6: note: 'AES_encrypt' declared here
void AES_encrypt(const unsigned char *in, unsigned char *out,
     ^
crypto-openssl.cpp:80:40: warning: 'EVP_sha1' is deprecated [-Wdeprecated-declarations]
        HMAC_Init(&(impl->ctx), key, key_len, EVP_sha1());
                                              ^
/usr/include/openssl/evp.h:666:15: note: 'EVP_sha1' declared here
const EVP_MD *EVP_sha1(void) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
              ^
crypto-openssl.cpp:80:2: warning: 'HMAC_Init' is deprecated [-Wdeprecated-declarations]
        HMAC_Init(&(impl->ctx), key, key_len, EVP_sha1());
        ^
/usr/include/openssl/hmac.h:95:6: note: 'HMAC_Init' declared here
void HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
     ^
crypto-openssl.cpp:88:2: warning: 'HMAC_CTX_cleanup' is deprecated [-Wdeprecated-declarations]
        HMAC_cleanup(&(impl->ctx));
        ^
/usr/include/openssl/hmac.h:93:27: note: expanded from macro 'HMAC_cleanup'
#define HMAC_cleanup(ctx) HMAC_CTX_cleanup(ctx) /* deprecated */
                          ^
/usr/include/openssl/hmac.h:91:6: note: 'HMAC_CTX_cleanup' declared here
void HMAC_CTX_cleanup(HMAC_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
crypto-openssl.cpp:93:2: warning: 'HMAC_Update' is deprecated [-Wdeprecated-declarations]
        HMAC_Update(&(impl->ctx), buffer, buffer_len);
        ^
/usr/include/openssl/hmac.h:99:6: note: 'HMAC_Update' declared here
void HMAC_Update(HMAC_CTX *ctx, const unsigned char *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
crypto-openssl.cpp:99:2: warning: 'HMAC_Final' is deprecated [-Wdeprecated-declarations]
        HMAC_Final(&(impl->ctx), digest, &len);
        ^
/usr/include/openssl/hmac.h:100:6: note: 'HMAC_Final' declared here
void HMAC_Final(HMAC_CTX *ctx, unsigned char *md, unsigned int *len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
crypto-openssl.cpp:105:6: warning: 'RAND_bytes' is deprecated [-Wdeprecated-declarations]
        if (RAND_bytes(buffer, len) != 1) {
            ^
/usr/include/openssl/rand.h:104:6: note: 'RAND_bytes' declared here
int  RAND_bytes(unsigned char *buf,int num) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
crypto-openssl.cpp:107:31: warning: 'ERR_get_error' is deprecated [-Wdeprecated-declarations]
                while (unsigned long code = ERR_get_error()) {
                                            ^
/usr/include/openssl/err.h:266:15: note: 'ERR_get_error' declared here
unsigned long ERR_get_error(void) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
              ^
crypto-openssl.cpp:109:4: warning: 'ERR_error_string_n' is deprecated [-Wdeprecated-declarations]
                        ERR_error_string_n(code, error_string, sizeof(error_string));
                        ^
/usr/include/openssl/err.h:280:6: note: 'ERR_error_string_n' declared here
void ERR_error_string_n(unsigned long e, char *buf, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
11 warnings generated.
c++ -Wall -pedantic -Wno-long-long -O2 -o git-crypt git-crypt.o commands.o crypto.o gpg.o key.o util.o parse_options.o crypto-openssl.o  -lcrypto
```

git-crypt unlock works fine after converting the key, though it seems to take rather a long time (17sec for 500Mb repo size)?

Thanks for the quick response!

**Comment by AGWA** [comment]
Thanks for trying this out.  I'll merge it into the master branch.

The warnings are to be expected, as Apple has deprecated OpenSSL in OS X.  If/when Apple actually removes OpenSSL I'll do something, but in the meantime it's not a problem.

How many total files does your repo contain?  Unfortunately, Git 2.2.2 broke `git-crypt unlock`, and to work around it I had to do something that is quite inefficient when a repo has a lot of files.  There's a more efficient way to do it, but it requires a newer version of Git.  I may have to condition the code on the version of Git that's installed...

**Comment by Aeon** [comment]
Thank you for the quick response!
